---

site_name: Owen's Home
site_url: https://owenlamont.github.io/home/

theme:
  name: material
  custom_dir: overrides
  favicon: img/favicon.ico
  palette:

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - blog
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - social
  - tags

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/owenlamont
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCYoZjpdGVH2X1MBgRD71lHw
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@owenrlamont
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/owen-lamont/
